#!/usr/bin/env bash
#all conditon for echo fizz,buzz or fizzbuzz for nummer 1 to 100
x=0
while [ $x -ne 100 ];
do
    ((x++))
    if (( x % 3 == 0 && x % 5 == 0 ))
    then 	
        echo "FizzBuzz"
    elif (( x%3 == 0 ))
    then 
        echo "Fizz"
    elif (( x%5 == 0 ))
    then
        echo "Buzz"
    else
        echo $x

    fi
done	
