#!/usr/bin/env bash
# the while loop do the displaying words , and the if condition is for the 9 echo
n=0
while [ $n -le 9 ]
do
    if [ $n == 9 ]
    then
        echo "Hi"      
    fi
    echo "Best School"
    (( n++ ))
done
