#!/usr/bin/env bash
# 
n=1
while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n == 4 ]
    then
    echo "bad luck"
    fi
    if [ $n == 8 ]
    then
    echo "good luck"
    fi
    (( n++ ))
   
done
