#!/usr/bin/env bash
# 
n=1
while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n == 4 ]
    
    	echo "bad luck"
    
    elif [ $n == 8 ]
    
    	echo "good luck"
    else
    	echo "Best School"
    (( n++ ))
    fi
done
