#!/usr/bin/env bash
#case do what if do and with the while loop n grow at 20
n=0
while [ $n -ne 20 ];
do
	(( n++ ))
	case $n in
	"4") 
	   	echo $n
		echo "bad luck from China"
	;;
	"9")
	   	echo $n
		echo "bad luck from Japan"
        ;;
	"17")
	    	echo $n
		echo "bad luck from Italy"
    	;;
	*) 
		echo $n
	;;
	esac;
done	
