#!/usr/bin/env bash
#
n = 0
while ( $n -eq 20)
do
	case $n in
	4) echo "bad luck from China" 
	   echo $n
	;;
        9) echo "bad luck from Japan"
	   echo $n
        ;;
	17) echo "bad luck from Italy"
	    echo $n
    	;;
	*) echo $n
	;;
	esac
	(( n++ ))
done	
