#!/usr/bin/env bash
#work for with 2 counter (n and t)
n=0
h=0
t=0
echo "Hour: $h"
while [ $t -ne "$head" ];
do
	if [ $n == 60 ];then
		((h++))
		((n=n-60))
		echo "Hour: $h"
	else
		echo $n
	fi;
	(( n++ ))
	(( t++ ))
done
