#!/usr/bin/env bash
#
echo $$ > /var/run/myscript.pid
while :
do
    echo "To infinity and beyond"
                    sleep 2
    trap 'echo "I hate the kill command"' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm "/var/run/myscript.pid"' SIGQUIT SIGTERM
done
