#!/usr/bin/env bash
#
echo $$ > /var/run/myscript.pid
while :
do
    echo "To infinity and beyond"
    trap 'echo "I hate the kill command"; rm /var/run/myscript.pid' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm /var/run/myscript.pid' SIGQUIT
    sleep 2
done

