#!/usr/bin/env bash
#
read start stop restarted
if [ read == $start ]
then
    job start manage_my_process
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ read == $stop ]
then
    job stop manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ read == $restart ]
then
     job stop manage_my_process
     rm /var/run/my_process.pid
     job start manage_my_process
     echo $$ > /var/run/my_process.pid
     echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
