#!/usr/bin/env bash
#
start1 () {
    job start manage_my_process
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
   }

stop1 () {
    job stop manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}

restarted () {
        job stop manage_my_process
        rm /var/run/my_process.pid
        job start manage_my_process
        echo $$ > /var/run/my_process.pid
        echo "manage_my_process restarted"
    }

read -r i

case $i in
    start)
        start1 ;;
        
    stop)
        stop1 ;;

    restarted)
        restarted ;;

    *)
         echo "Usage: manage_my_process {start|stop|restart}"
esac
